dist: trusty
sudo: required
language: c++
  
cache:
  directories:
  - '$HOME/.sonar/cache'

addons:
  sonarcloud:
    organization: "mrpoudel"
    token:
       secure: "Zh0ob4SvguSFnmYyy0kyHCNat5FxZLX81hqYqYQqC/VxjeR0xzrRHttSqKGmfD6IDcHf2KxBXz9kmm03m7z24Mfpr2vGbRTyN8Sz//vpmJAUo+6AK59NOYLeYt5yK8rnQEcwbUQ6UqU9RMc/L7AtFF9CFX6PEmraoA3Z8jDFp3lqSh1UPMT9J1ip2Dn+hMBiBJnh53MeU44qv7nQ+XcPT0fV3jqm86oQ37hw1Z8wy7u0UbaX8/jY9yL7Zy5xUaPKKQLR7ZtryaoladLP9a2iICx/E1p5eHxxwN7JnHz5myAN5wYCI3Ag3kQBj2/tw1R+7zkPWNx2vXIZj7ndj2InpGr5u18t7qWu9J1qSySZv5HEnIZd5c9+1vS0YOMhEr0i4AFThA6XjxjKEeZGG0Va11rIZDzHQsIAc6e9uvWQTq9cLEdfTmpsD8kPkp4M8jg6cVVR4H3SHh9O2t8wLs9WQUoLY0YwdP76Xf6SBN76S3EUjtBvI0BVqP/Rntx01SIucMPJeltx7kTmrgbbKt53e7GtVzCOE6S8tDMSWMr/1gxycebIYyo99DLjkiNQVUJbLO5KYEw6GES+GvzRT83oBuODFBtOu8aF4zTy/FR4Smz+LWB3IymVfhZivt7qlpkyEpH+D03ItM5mPwOydROpsQDrVPLomYfgFvp6C5oCpR0="
env:
  - SONAR=true

# disable git fetch depth limit to 0, otherwise you are git cloning twice.
git:
  depth: false  
  
before_install:
  - sudo apt-get update -qq # make the output less noisy
#   - sudo apt-get upgrade
  - sudo apt-get install cmake
  - sudo apt-get install valgrind
  - sudo apt-get install libgles2-mesa-dev  
  - sudo apt-get install libegl1-mesa-dev  
  - sudo apt-get install libsdl2-dev
  - sudo pip install --upgrade pip
  - sudo pip install gcovr
       
script:
 - sudo apt install tree
 - mkdir build
 - cd build
 - pwd
#  - cmake ..
#  - ./test/ParticleTest
 # Wraps the compilation with the Build Wrapper to generate configuration (used
 # later by the SonarQube Scanner) into the "bw-output" folder
 - build-wrapper-linux-x86-64 --out-dir bw-output cmake .. && make clean all && make coverage && ./test/ParticleTest
 - tree -L 2
 - pwd
 #- cd ..
 - pwd
 - tree -L 1
 - sonar-scanner  -X #-Dsonar.cfamily.build-wrapper-output=bw-output
