dist: trusty
sudo: required
language: c++ 
  
cache:
  directories:
  - '$HOME/.sonar/cache'

addons:
  apt:
    packages:
      - cmake
      - valgrind
      - libgles2-mesa-dev 
      - libegl1-mesa-dev 
      - libsdl2-dev
      - gcovr
      - tree
  sonarcloud:
    organization: "mrpoudel"
    token:
       secure: "eOchtfqlF6Kx8fN2eEuZ7zahEvyvwmossuvNGC/eEKF8zapsF+O4UehiPw1FJnPKFmtky+PwV6iSAEjvIb8udGCicrKLuEQXrgiSDWYeQ3DLlOP7tbtGOhdiQfnjYLfQtQFbKbjFTmPHGI0sTMatzt7BvK40xZ5yFeDSol8Do+kp1X4DEiPaNM5T4Jnpxp/XnotVY7zbbEiMdzHfd2dWl65CoVeYbgjua3oO8TNb4HyysHOadL+8LvPJn7mrv+Lq0XSpRHgztiK8nu9PkjG7bJwCILemYR9WbIYpyMoPnSDUGK46rKFU1t9UoiNbTMyIpKschFIBUGBmWetLOH8ZrNgmCiI97Bd7z/9D6anxDlmm2fi4vgYcqEskcqlJtV2TDiWnuhIlivraa2bYCMoOlZm2kV2MwJy/N495O7P2WJuIG9ePIQORwyYvRR1mDn2kIkTd+LD7muGVnzMi5iIPZzyWqDQTUwDNa/3L05yQBoeFTu+h3kfTxwwS1/n6o3jmzKCbXtMg5ylt8hZLO4PWR9hWIo/LDNe3yjxRB+7OQV53XsLC3eJgp3q7YGBW8hW34uakh5poH3oPm0s7cwFMwROoethBRUjbIDcxtiA3PzbQiXo7yr4WaLI6uPtMNNTW8+TNEHkRdd4eq42sApiXbKe9v9dhowo0/GzFfhprK2c="
       #secure: "Zh0ob4SvguSFnmYyy0kyHCNat5FxZLX81hqYqYQqC/VxjeR0xzrRHttSqKGmfD6IDcHf2KxBXz9kmm03m7z24Mfpr2vGbRTyN8Sz//vpmJAUo+6AK59NOYLeYt5yK8rnQEcwbUQ6UqU9RMc/L7AtFF9CFX6PEmraoA3Z8jDFp3lqSh1UPMT9J1ip2Dn+hMBiBJnh53MeU44qv7nQ+XcPT0fV3jqm86oQ37hw1Z8wy7u0UbaX8/jY9yL7Zy5xUaPKKQLR7ZtryaoladLP9a2iICx/E1p5eHxxwN7JnHz5myAN5wYCI3Ag3kQBj2/tw1R+7zkPWNx2vXIZj7ndj2InpGr5u18t7qWu9J1qSySZv5HEnIZd5c9+1vS0YOMhEr0i4AFThA6XjxjKEeZGG0Va11rIZDzHQsIAc6e9uvWQTq9cLEdfTmpsD8kPkp4M8jg6cVVR4H3SHh9O2t8wLs9WQUoLY0YwdP76Xf6SBN76S3EUjtBvI0BVqP/Rntx01SIucMPJeltx7kTmrgbbKt53e7GtVzCOE6S8tDMSWMr/1gxycebIYyo99DLjkiNQVUJbLO5KYEw6GES+GvzRT83oBuODFBtOu8aF4zTy/FR4Smz+LWB3IymVfhZivt7qlpkyEpH+D03ItM5mPwOydROpsQDrVPLomYfgFvp6C5oCpR0="
env:
  - SONAR=true

# disable git fetch depth limit to 0, otherwise you are git cloning twice.
git:
  depth: false  
  quite: true
       
script:
 #- sudo apt install tree
 - rm -rf build
 - mkdir build
 - cd build
 # Wraps the compilation with the Build Wrapper to generate configuration (used
 # later by the SonarQube Scanner) into the "bw-output" folder
 - cmake ..
 - build-wrapper-linux-x86-64 --out-dir bw-output make clean all
 - make
 - make coverage # This will run all the tests
 
 #- mkdir gcov && cd gcov && gcov $(find .. -name '*.gcov')
 #- tree -L 2
 #- cat bw-output/build-wrapper-dump.json
 #- cat bw-output/build-wrapper.log
 #- ls
 - cd ..
 - ls
 - chmod a+x collect-gcov-reports.sh
 - sudo ./collect-gcov-reports.sh
 - sonar-scanner  -X #-Dsonar.projectKey=MrPoudel_ParticleExplosion #-Dsonar.cfamily.build-wrapper-output=build/bw-output #-Dsonar.cfamily.gcov.reportsPath=build/gcov #-Dsonar.testExecutionReportPaths=build/coverage.xml
